import ClientLayout from './ClientLayout';
export const metadata = {
  title: 'My Social Media',
  description: 'Generated by Ritesh Kumar Sah',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
